app/routes/scan.py
import os
import sys

from flask import Blueprint, render_template, request, jsonify, url_for, send_file, redirect
from sqlalchemy import asc

from app.config import UPLOAD_DIR_PDF, UPLOAD_DIR_JPG, UPLOAD_DIR_TXT
from app.models.ScannerThread import ScannerThread

scan_app = Blueprint('scan_app', __name__, template_folder='../templates/scan', url_prefix='/scan')

threadScan = ScannerThread()
threadScan.start()


def add_file(file):
    threadScan.append_file(file)


@scan_app.route('/', methods=['GET'])
@scan_app.route('/upload', methods=['GET'])
def show():
    """
    Page for uplaod file
    :return: upload.html
    """
    from app.models.Form import ScanDocumentForm
    form = ScanDocumentForm()
    return render_template('upload.html', form=form)


@scan_app.route('/upload', methods=['POST'])
def upload():
    """
    This page allow users to upload a pdf file for to be scan by ocr

    :return: files.html
    """
    from app.models.Form import ScanDocumentForm

    form = ScanDocumentForm()

    if form.validate_on_submit():

        # save in dbb
        from app.models.DataBase import PdfFile, db

        file = form.filePdf.data

        pdf = PdfFile(name=file.filename)

        db.session.add(pdf)
        db.session.commit()

        file.save(os.path.join(UPLOAD_DIR_PDF, str(pdf.id) + '.pdf'))

        add_file(pdf.id)

        return redirect(url_for('scan_app.files'))
    else:
        return str(form.errors)


"""
    This page allow correction for user to 
"""


@scan_app.route('/selectionExtract/<int:pdf_id>', methods=['GET', 'POST'])
def selection_extract(pdf_id):
    # ckeck if the file exist

    from app.models.DataBase import OCRPage
    try:
        pages = OCRPage.query.filter_by(pdf_file_id=pdf_id).all()
        return render_template('selectionExtract.html', pages=pages, pdf_id=pdf_id)
    except Exception as E:
        return str(E)


@scan_app.route('/downlaod/<int:pdf_id>')
def download(pdf_id):
    """
    This page is for downlaod the document after correction

    :param pdf_id:
    :return: file of all text of pdf separate by -- num page --
    """
    from app.models.DataBase import OCRPage, PdfFile

    pdf_file = PdfFile.query.filter_by(id=pdf_id).first()
    filename = pdf_file.name

    file_path = os.path.join(UPLOAD_DIR_TXT, str(filename) + '.txt')

    pages = OCRPage.query.filter_by(pdf_file_id=str(pdf_id)).all()
    f = open(file_path, "wb")

    for page in pages:
        f.write(
            ("-" * 50 + "\n \t\t\t Num : " + page.num_page + "\n" + "-" * 50 + "\n").encode(sys.stdout.encoding,
                                                                                            errors='Error'))
        f.write(
            (str(page.text if page.text_corrector is None else page.text_corrector) + '\n').encode(sys.stdout.encoding,
                                                                                                   errors='Error'))

    f.close()
    return send_file(file_path)


@scan_app.route('/files', methods=['GET'])
def files():
    """
    This page list all file in bdd
    :return: files.html
    """
    from app.models.DataBase import PdfFile
    files = PdfFile.query.order_by(asc(PdfFile.status)).order_by(asc(PdfFile.name)).all()
    return render_template('files.html', files=files)


@scan_app.route('/images/<int:pdf_id>/<int:page_number>')
def get_images(pdf_id, page_number):
    """

    :param pdf_id: the id of pdf
    :param page_number: page number
    :return: the image of page of pdf
    """
    folder = os.path.join(UPLOAD_DIR_JPG, str(pdf_id))
    filename = os.path.join(folder, str(page_number) + '.jpg')
    return send_file(filename, mimetype='image/jpg')


@scan_app.route('/page/<int:pdf_id>/<int:page_number>')
def get_boxs(pdf_id, page_number):
    """
    list of box and text of page of pdf
    :param pdf_id:
    :param page_number:
    :return: json list box of all word in page and text of page
    """
    from app.models.DataBase import OcrBoxWord, OCRPage

    # get all box of page

    page = OCRPage.query.filter_by(pdf_file_id=pdf_id, num_page=page_number).first()

    boxs = OcrBoxWord.query.filter_by(pdf_page_id=page.id).all()

    json_array = {'box': [e.serialize() for e in boxs],
                  'text': page.text if page.text_corrector is None else page.text_corrector}

    return jsonify(json_array)


@scan_app.route('/delete/<int:pdf_id>')
def delete_file(pdf_id):
    """
    Delete the file on dbb
    :param pdf_id:
    :return: files.html
    """
    try:
        from app.models.DataBase import PdfFile, db
        PdfFile.query.filter_by(id=pdf_id).delete()
        return redirect(url_for('scan_app.files'))
    except Exception as error:
        return jsonify({'error': 'During delete ( ' + str(error) + ' )'})


@scan_app.route('/correct/<int:pdf_id>/<int:num_page>', methods=['POST', 'GET'])
def correction(pdf_id, num_page):
    """
    Correct the text of page
    :param pdf_id: the id of pdf
    :param num_page: the page of pdf
    :return: success or error
    """
    from app.models.DataBase import OCRPage, db
    ocr_page = OCRPage.query.filter_by(pdf_file_id=pdf_id, num_page=num_page).first()
    ocr_page.text_corrector = request.form['text']
    db.session.commit()
    return 'success'

app/templates/scan/download.html
{% extends 'elements/base.html' %}

{% block head %}
{% endblock %}

{% block body %}
{% endblock %}

app/templates/scan/files.html
{% extends 'elements/base.html' %}

{% block head %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
{% endblock %}

{% block body %}
    <div class="container">
        <a class="btn btn-primary" href="{{url_for('scan_app.upload')}}" >Uploaod</a>

        <div class="row">

            <div class="col-md-12 mt-4">

                <table class = "table table-hover">

                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Status</th>
                            <th scope="col">Open</th>
                            <th scope="col">Downlaod</th>
                            <th scope="col">Delete</th>

                        </tr>
                    </thead>

                    <tbody>

                    {% for file in files %}

                        <tr>

                            <td class="col-md-1">{{ file.id }}</td>
                            <td class="col-md-6">{{ file.name }}</td>
                            <td class="col-md-2">{{ file.status | value_status_file }}</td>
                            <td class="col-md-1"><a href="{{ url_for('scan_app.selection_extract', pdf_id= file.id ) }}"><i class="ml-2 far fa-folder-open"></i></a></td>
                            <td class="col-md-1"><a href="{{ url_for('scan_app.download', pdf_id= file.id ) }}"><i class="ml-4 fa fa-download"></i></a></td>
                            <td class="col-md-1"><a href="{{ url_for('scan_app.delete_file', pdf_id= file.id ) }}"><i class="ml-3 far fa-times-circle"></i></a></td>

                        </tr>

                    {% endfor %}

                  </tbody>

                </table>

            </div>

        </div>

    </div>
{% endblock %}

app/templates/scan/selectionExtract.html
{% extends 'elements/base.html' %}

{% block head %}

     <script src="{{ url_for('static', filename='js/selection.js') }}"></script>
     <script src="{{ url_for('static', filename='js/correction.js') }}"></script>
     <link rel="stylesheet" href="{{ url_for('static', filename='css/loader.css') }}"/>
{% endblock %}

{% block body %}

<div class="container">

    <div class="row mb-3">
        <h3 class="mt-1">Extract</h3>
    </div>

    <div class="row mb-3">

        {# col of all page's image scroll #}
        <div class="col-md-3">

            <ul class="list-group scroll-list-image " style="height: 770px;">

                {% for  page in pages %}

                    {% if loop.index == 0 %}
                        {% set first_page_num = page.num_page %}
                    {% endif %}

                    <li class="page-element-selection list-group-item" data-pdf_id="{{ pdf_id }}" data-page_number="{{ page.num_page }}">
                        <div class="card">
                            <div class="card-header">
                                {% set num = page.num_page|int + 1 %}
                                {{ num }}
                            </div>
                            <div class="card-body">
                                <img width="100%" src="{{ url_for('scan_app.get_images' , pdf_id=pdf_id , page_number=page.num_page) }}">
                            </div>
                        </div>
                    </li>

                {% endfor %}
            </ul>

        </div>

        {# tabs text and image #}
        <div class="col-md-9">

            <div id="load-process"></div>

            {# list tab#}
            <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" id="canvas-tab" data-toggle="tab" href="#canvas" role="tab" aria-controls="canvas" aria-selected="true">Image</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="text-tab" data-toggle="tab" href="#text" role="tab" aria-controls="text" aria-selected="false">Text</a>
              </li>
            </ul>

            {# tab content #}
            <div class="tab-content" id="myTabContent">

                <div class="tab-pane fade show active" id="canvas" role="tabpanel" aria-labelledby="canvas-tab">
                    <canvas id="canvas-selection" class="m-2" style="border:1px solid gray;" value="">
                    Your browser does not support the canvas element.
                    </canvas>
                </div>

                <div class="tab-pane fade" id="text" role="tabpanel" aria-labelledby="text-tab">
                    <form method="post">
                        <textarea id="textarea-text-page" class="m-2" style="width:100%; height:500px;">
                        </textarea>
                        <input class="btn btn-primary btn-correction" type="submit" value="Edit">
                    </form>
                </div>

            </div>

         </div>

      </div>

    </div>

{% endblock %}

app/templates/scan/upload.html
{% extends 'elements/base.html' %}

{% block head %}

{#    <script src="{{ url_for('static', filename='js/upload.js') }}"></script>#}
    <script src="{{ url_for('static', filename='js/bootstrap-fileselect.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/file-input.css') }}">

{% endblock %}

{% block body %}

{% if error %}
    <div class="alert alert-danger" role="alert">
        {{error}}
    </div>
{% endif %}

    <div class="container">

      <div class="row">
        <div class="col-md-12">
          <h1 class="display-1">Scan</h1>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 align-middle">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed dictum velit, finibus faucibus quam. Suspendisse potenti. Ut nibh lorem, sagittis nec condimentum et, mattis sit amet lorem. Duis et lorem ac lacus viverra fringilla.</p>
            <p>Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer dictum a ex eget euismod. Nulla tristique, magna sodales hendrerit blandit, lacus felis mattis enim, a tempus diam dui non quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed dictum velit, finibus faucibus quam. Suspendisse potenti. Ut nibh lorem, sagittis nec condimentum et, mattis sit amet lorem. Duis et lorem ac lacus viverra fringilla.</p>
        </div>
        <div class="col-md-6">


            <form method="POST" enctype="multipart/form-data" action="{{ url_for('scan_app.upload') }}">
                <div class="form-group">
                    {{ form.filePdf.label }}{{ form.filePdf(id='input-file',accept='.pdf') }}
                </div>
                <div class="form-group">

                    <label>Range Page</label>
                      <div class="row">
                        <div class="col">
                            {{ form.file_range_min.label }}{{ form.file_range_min(class_='form-control',value="0") }}
                            </div>
                          <div class="col">
                          {{ form.file_range_max.label }}{{ form.file_range_max(class_='form-control',value="0") }}
                        </div>
                      </div>
                </div>

                <button id="submit-uplaod" type="submit" class="btn btn-primary">Submit</button>
            </form>


            <div class="mx-auto text-center mt-3">
                <div class="progress">
                  <div id="progressBar" class="progress-bar progress-bar-striped bg-primary" role="progressbar" style="width:0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>

        </div>
      </div>

    </div>

   <script>
        $('#input-file').fileselect();
    </script>
{% endblock %}